### ISSUE TITLE
path params

### ISSUE THREAD

**Issue by yanetut** [fjc0k/yapi-to-typescript#13]
请问路径参数好像不支持？
/xxx/:id1/:id2
/xxx/{id1}/{id2}
![image](https://user-images.githubusercontent.com/12288710/65029445-58bf3000-d970-11e9-8fab-1e20c9692bec.png)

**Comment by fjc0k** [comment]
👌待我研究研究

**Comment by fjc0k** [comment]
已支持，将 `yapi-to-typescript` 升级至最新版即可，不用特别的设置。
