### ISSUE TITLE
使用 token 报错：请登录

### ISSUE THREAD

**Issue by hhking** [fjc0k/yapi-to-typescript#14]
```js
/api/plugin/export
```
我看了下，发现是这个接口用 token 请求会报错：`请登录...`

所以现在是不支持多种多种方式登录？文档看的有点晕，直接看源码的

是不是我的使用姿势不对？

Yapi版本：1.5.6

**Comment by fjc0k** [comment]
看要求，最低 1.5.12：https://github.com/fjc0k/yapi-to-typescript#%E7%8E%AF%E5%A2%83%E8%A6%81%E6%B1%82

**Comment by hhking** [comment]
有看到这个，我看之前issue是支持旧版的。那就是现在不支持了

**Comment by fjc0k** [comment]
支持旧版看 v0 分支：https://github.com/fjc0k/yapi-to-typescript/tree/v0

**Comment by hhking** [comment]
👌3Q
