### ISSUE TITLE
错误提示，请登录

### ISSUE THREAD

**Issue by Darkhorse-Fraternity** [fjc0k/yapi-to-typescript#15]
serverUrl 需要加token 吗？我加不加都提示请登录. 
http://foo.com/api/interface/list
需要加api/interface/list，加上不加上都提示，请登录

yapi-to-typescript v1.18.2

**Comment by fjc0k** [comment]
先看看这个：https://github.com/fjc0k/yapi-to-typescript/issues/14

**Comment by Darkhorse-Fraternity** [comment]
Yapi版本：1.8.3  是比较新的版本了

**Comment by fjc0k** [comment]
那就是你 token 错了或者没有设置，建议你删掉 ytt.config.ts，重新生成配置文件，按照标准来

**Comment by Darkhorse-Fraternity** [comment]
是我的问题。token 写错位置了

**Comment by Darkhorse-Fraternity** [comment]
![image](https://user-images.githubusercontent.com/5756752/70115896-17e7d500-169c-11ea-80a7-0833864d4dd7.png)
✔ 获取数据并生成代码完毕                                                                                 13:42:05
✔ 写入文件完毕                                                                                           13:42:05
✨  Done in 2.71s.

在 src/api/index.ts 下面没发现接口也

**Comment by fjc0k** [comment]
解决了？
