### ISSUE TITLE
没有报错，但/src/api/index.ts 下没有生成文件

### ISSUE THREAD

**Issue by Darkhorse-Fraternity** [fjc0k/yapi-to-typescript#16]
![image](https://user-images.githubusercontent.com/5756752/70116074-a3f9fc80-169c-11ea-8ddc-6cfb1fbab619.png)

✔ 获取数据并生成代码完毕                                                                                 13:42:05
✔ 写入文件完毕                                                                                           13:42:05
✨  Done in 2.71s.

/src/api/index.ts 下没有生成文件，手动生成再执行也不行。

**Comment by Darkhorse-Fraternity** [comment]
![image](https://user-images.githubusercontent.com/5756752/70116151-d3a90480-169c-11ea-9c31-c4804cfbf047.png)

**Comment by Darkhorse-Fraternity** [comment]
是不是我配置哪里写错了。

**Comment by lisiur** [comment]
@Darkhorse-Fraternity 我也遇到这个问题了，请问你是如何解决的
