### ISSUE TITLE
path 含有数字时，大小写出现错误

### ISSUE THREAD

**Issue by Darkhorse-Fraternity** [fjc0k/yapi-to-typescript#17]
![image](https://user-images.githubusercontent.com/5756752/70127459-0ca1a300-16b6-11ea-8aa0-a9e6c67fca6c.png)
![image](https://user-images.githubusercontent.com/5756752/70127483-175c3800-16b6-11ea-9df1-f8d272149285.png)

**Comment by Darkhorse-Fraternity** [comment]
3d 和 3D 出现命名匹配错误

**Comment by Darkhorse-Fraternity** [comment]
直接用name 的话，我担心会出现重复

**Comment by fjc0k** [comment]
应该修复了，请升级版本后再试。
