### ISSUE TITLE
projectInfo.cats.find is not a function 

### ISSUE THREAD

**Issue by bazingaedward** [fjc0k/yapi-to-typescript#22]
if serverUrl config end with '/'，like 
`serverUrl: 'http://api.facebook.com/' `
.then fetch result will be wrong html documents.

May be give user a  suggestion in serverConfig -> serverUrl config will be more reasonable.

https://fjc0k.github.io/yapi-to-typescript/interfaces/serverconfig.html#serverurl

Best work , it's awesome!

**Comment by fjc0k** [comment]
fixed in [3.1.1](https://github.com/fjc0k/yapi-to-typescript/blob/master/CHANGELOG.md#311-2020-04-13), thx!  🤝
