### ISSUE TITLE
生成定义文件报错

### ISSUE THREAD

**Issue by henryzp** [fjc0k/yapi-to-typescript#23]
![image](https://user-images.githubusercontent.com/3849702/79533190-dc2d3500-80a9-11ea-874e-b553891016f5.png)

配置文件如下：

```ts
import { Config } from "yapi-to-typescript";

const config: Config = [
  {
    serverUrl: "my yapi server",
    typesOnly: true,
    reactHooks: {
      enabled: false,
    },
    prodEnvName: "local",
    outputFilePath: "src/api/index.ts",
    // requestFunctionFilePath: "src/api/request.ts",
    dataKey: "data",
    projects: [
      {
        token: "my token",
        categories: [
          {
            id: 0,
          },
        ],
      },
    ],
  },
];

export default config;
```

另外想问问有没有demo提供的？？

比如说requestFunctionFilePath，这个参数，文件内容写啥？？有没有模板。。

**Comment by fjc0k** [comment]
typesOnly 设为 false 正常？

**Comment by henryzp** [comment]
@fjc0k 找到原因了，发现是：

projects配置，单个对象，必须要传`getRequestFunctionName`这个函数，不然报错。。我这边是这个情况。。

然后翻了一个issue，发现多目录的接口还是有必要的。

比如：
![image](https://user-images.githubusercontent.com/3849702/79536666-2d8df200-80b3-11ea-9f15-3958522e634f.png)

![image](https://user-images.githubusercontent.com/3849702/79536734-52826500-80b3-11ea-995f-69381d13850e.png)

另外能不能提供一份request.ts模板呢？

**Comment by henryzp** [comment]
你们这个有没有相关的微信群沟通的？

**Comment by fjc0k** [comment]
因为默认类型名称是根据 getRequestFunctionName 推导出来的，除非你设置了 获取类型名称 的属性。

**Comment by fjc0k** [comment]
暂时没有哈。

**Comment by fjc0k** [comment]
request.ts 会自动生成的，那个就是模板。

**Comment by henryzp** [comment]
我这边没有生成啊？？

**Comment by fjc0k** [comment]
typesOnly 设为 true 怎么生成哦

**Comment by henryzp** [comment]
不是，我懂了。。。我一开始就有一个request.ts文件，空的。。

然后你不会往里面写。。大概逻辑我懂了，我想问一下，就是 你的TResponseData这个类型，是`dataKey`对应的那一层吧？

**Comment by henryzp** [comment]
哥们，你方便加一下微信，或者说创建一个微信群吗？

**Comment by fjc0k** [comment]
TResponseData 就是返回结果的类型
