### ISSUE TITLE
使用时提示 TS 编译出错

### ISSUE THREAD

**Issue by jesseluo** [fjc0k/yapi-to-typescript#24]
执行 yarn ytt 报错。确认了一下项目本身的 ts 配置是对的

`
ERROR  ⨯ Unable to compile TypeScript:                                                                     18:17:30  
error TS5052: Option 'checkJs' cannot be specified without specifying option 'allowJs'.  
`
![image](https://user-images.githubusercontent.com/1271415/80305533-d80ebf00-87ef-11ea-8024-4a3979c2c331.png)

**Comment by fjc0k** [comment]
你本身 tsconfig.json 问题，人家不说了，`Option 'checkJs' cannot be specified without specifying option 'allowJs'` --> `checkJs 必须搭配 allowJs 才能干活。`

**Comment by jesseluo** [comment]
> 你本身 tsconfig.json 问题，人家不说了，`Option 'checkJs' cannot be specified without specifying option 'allowJs'` --> `checkJs 必须搭配 allowJs 才能干活。`

我确认了一下项目本身的 ts 配置是对的，都在，本身也能跑

**Comment by fjc0k** [comment]
试试最新版呢
