### ISSUE TITLE
接口路径含有关键词是delete之类的会报错

### ISSUE THREAD

**Issue by WuSiung** [fjc0k/yapi-to-typescript#27]
例如http://mock.*****.com/mock/60/V1/traveler/delete
![1589014550(1)](https://user-images.githubusercontent.com/28723523/81469272-c4fbe600-9216-11ea-8f00-4efab2909f12.jpg)
改了成别的就可以，这个算bug吗。ts命名关键词就有这些。

**Comment by WuSiung** [comment]
修改之后可以顺利生成

**Comment by fjc0k** [comment]
这是 js 的关键词，用于删除对象的属性的，就像这样：

```js
const obj = {x: 1}
delete obj.x
console.log(obj) // => {}
```

你可以更改请求函数生成函数，遇到 delete 加个后缀啥的。

**Comment by fjc0k** [comment]
![image](https://user-images.githubusercontent.com/13151189/81470197-1eb2df00-921c-11ea-955c-845b302901e1.png)

**Comment by henryzp** [comment]
这里会引发一些思考，就是如果是resful的接口，那么post put delete get的URL都是相同的，怎么来区别name？

解法当然有很多。。但是我这边碰到的问题是其他接口不是resful，部分是，那么改name的话，会造成我这边的返工。。

请问有什么更好的解法么？

**Comment by fjc0k** [comment]
@henryzp  不是提供了 getRequestFunctionName 嘛，以 name 为例，但不是说只能通过 name 获取函数名称，你可以以路径或者其他解析方式。 interfaceInfo 传给你的所有信息，你都可以作为线索。
