### ISSUE TITLE
关于 yapi-to-typescript 的包引用

### ISSUE THREAD

**Issue by kamilic** [fjc0k/yapi-to-typescript#35]
https://github.com/fjc0k/yapi-to-typescript/blob/master/src/Generator.ts#L262

现在看生成出来的代码都是直接引 `yapi-to-typescript` 这个库的，可否提供一个配置去改变其引用路径？就像 request 一样。

**Comment by fjc0k** [comment]
理由？

**Comment by kamilic** [comment]
reply @fjc0k 
我这边的用法是基于 yapi-to-typescript 封装一个约定大于配置的工具，对外其实是不需要关注到 yapi-to-typescript 这个包的（实际上存在于工具的依赖中）。
但是生成的代码直接引了这个包，导致用户方必需要下载这个包才能让 ts resolve 到（当然可以改 paths 之类的让 ts 去找，但是我不太希望这样）。
现在的用法只能让 yapi-to-typescript 作为一个 peer-dependency 存在，用这个封装工具时需要同时安装它，所以看看你这边能否支持这样的用法。

**Comment by fjc0k** [comment]
额额，这种极个性的需求还是建议 fork 一份做二次开发。

**Comment by kamilic** [comment]
噢 好滴
