### ISSUE TITLE
路径参数的处理

### ISSUE THREAD

**Issue by henryzp** [fjc0k/yapi-to-typescript#37]
想问一下，这一块request.ts文件有处理么？

我自己的做法是第二个参数，传入placeholder，然后解析对象处理。

问题是，请求的第二个参数必须要传路径参数，请问代码里面是做了什么处理？

**Comment by fjc0k** [comment]
路径参数不是已经支持了的嘛

**Comment by henryzp** [comment]
？？？payload.path不行吧，要用哪个属性。。。

**Comment by fjc0k** [comment]
在传给 request 前，已经根据参数对 path 进行处理替换了，无感知的，不用关心。

**Comment by henryzp** [comment]
@fjc0k ，不对吧，那我这边打印`payload.path`，还是带符号的啊，就是比如说后端有一个占位符：`{id}`。。。我在request.ts里面，拿到的`payload.path`，还是`{id}`

**Comment by fjc0k** [comment]
https://github.com/fjc0k/yapi-to-typescript/blob/master/src/helpers.ts#L63

你要传数据 id 呀，不然不会替换。

**Comment by henryzp** [comment]
。。。orz，懂了，那确实不用了。。。我回头自己处理一下吧
