### ISSUE TITLE
请问，如果后端接口路径相同，但是请求方式可能是get或者post, 如何加以区分

### ISSUE THREAD

**Issue by snoopy1412** [fjc0k/yapi-to-typescript#38]
生成ts文件的时候，发现 路径相同的话
例如 get     /user 和  post    /user  都生成的是同一份ts interfase, 会报错，如何根据不同的请求方式生成不同的interface呢？

**Comment by fjc0k** [comment]
自定义选项都给你的，注意看 api 文档。

![image](https://user-images.githubusercontent.com/13151189/86221437-7be16600-bbb7-11ea-8a5c-c06cd20a84f8.png)

**Comment by snoopy1412** [comment]
> 自定义选项都给你的，注意看 api 文档。

好的，谢谢
