### ISSUE TITLE
推荐使用 openapi ，而不是通过用户名密码登录

### ISSUE THREAD

**Issue by hellosean1025** [fjc0k/yapi-to-typescript#4]
https://yapi.ymfe.org/openapi-doc.html

**Comment by fjc0k** [comment]
🤔可以新增个登录方式：`openapi`，用户名、密码留着兼容老版本。

**Comment by fjc0k** [comment]
@hellosean1025 我用 postman 测试 openapi 时提示：

```json
{
    "errcode": 40011,
    "errmsg": "请登录...",
    "data": null
}
```

用项目的 token 之前是需要登录的？

**Comment by fjc0k** [comment]
@hellosean1025 将 cookies 导入 postman 后正常了，测试后发现，目前没有一个 api 能一次性提供某个分类下所有接口的定义，这导致在接口比较多的项目中会导致需要很多次请求才能获取完整的接口定义数据。

**Comment by hellosean1025** [comment]
升级到最近的版本测试下

**Comment by hellosean1025** [comment]
/api/interface/list_cat?page=1&limit=20&catid=163
这个接口可以满足你的需求，不过这个需求目前还没有加入到 openapi ，下个版本我迭代下

**Comment by fjc0k** [comment]
登录没问题了。之前用的 `yapi update` 升级的，只能升级到 1.4.1 ，指定 1.5 后才行。

**Comment by fjc0k** [comment]
已实现 openapi 登录：https://github.com/fjc0k/yapi-to-typescript#%E9%85%8D%E7%BD%AE%E9%A1%B9。后续看 openapi 接口开放情况做优化。

**Comment by hellosean1025** [comment]
https://github.com/hellosean1025/yapi-gen-js-code
@fjc0k 可以参考下，我刚写了一个，其实我觉得是可以废弃密码登录这种方案的

**Comment by fjc0k** [comment]
@hellosean1025 👍！

密码登录我觉得保留兼容老版本是可以的，就像我司，用的还是 1.3。。。

**Comment by fjc0k** [comment]
@hellosean1025 试了下新增的 `/api/interface/list_cat`，发现其只是将接口的基本信息返回，如此，仍旧要挨个遍历取得详细信息：

```json
            {
                "edit_uid": 0,
                "status": "done",
                "api_opened": false,
                "tag": [],
                "_id": 15,
                "method": "POST",
                "catid": 16,
                "title": "课程信息",
                "path": "/Courses",
                "project_id": 8,
                "uid": 11,
                "add_time": 1544589314
            },
```
