### ISSUE TITLE
可不可以增加输出路径的配置

### ISSUE THREAD

**Issue by sjhhjx99** [fjc0k/yapi-to-typescript#41]
我们的项目输出到同一个文件很容易造成重复变量名,希望增加输出路径的配置,或者
```
outputFilePath(interfaceInfo) {
   return `src/api/${interfaceInfo.parsedPath.name}.ts`
}
```
谢谢啦,多亏你的项目,我多摸了很多鱼

**Comment by fjc0k** [comment]
outputFilePath 可以配置在服务器、项目、分类级别的，也可以把生成函数名的函数调整下生成唯一名称。

**Comment by leitingx762** [comment]
> outputFilePath 可以配置在服务器、项目、分类级别的，也可以把生成函数名的函数调整下生成唯一名称。

大大 方便问一下这个要怎么配置吗?没有在文档看到这个配置的说明,我想生成在分类的级别
