### ISSUE TITLE
我没有办法访问你的api 文档

### ISSUE THREAD

**Issue by StitchC** [fjc0k/yapi-to-typescript#43]

**Comment by StitchC** [comment]
已经挂了

**Comment by StitchC** [comment]
> 挂个代理试试

已经挂了

**Comment by fjc0k** [comment]
我反正可以的🤣

**Comment by StitchC** [comment]
> 我反正可以的🤣

能贴一下到 README 吗

**Comment by StitchC** [comment]
> 我反正可以的🤣

试了很多次了 还是打不开 挂代理可以访问google YouTube 的 可以私发一下配置文档到我邮箱吗 麻烦了 因为挺着急的

**Comment by yaqingshan** [comment]
请问有qq群或者微信群吗？我想求助点儿问题。。 那个预览的图片 就是最终生成的代码吗 该咋用。。

**Comment by fjc0k** [comment]
https://fjc0k.gitee.io/yapi-to-typescript/handbook/
