### ISSUE TITLE
生成TS声明文件，支持对Model生成单独的interface吗？

### ISSUE THREAD

**Issue by JerryChan31** [fjc0k/yapi-to-typescript#44]
目前在用的类型文件生成工具：https://github.com/horiuchi/dtsgenerator
现在想用yapi来统一接口管理，同时支持生成类型定义文件。
目前看了一下ytt生成的接口类型声明文件，和dtsgenerator相比，dtsgenerator生成的类型声明文件会使用swagger接口中的model作为单独的interface，然后其他引用了同一个model的接口也会引用同一个interface。其次对同一个definition的接口会保持在同一个namespace中。
例如：
```ts
declare namespace API_FILE {
  export interface AResponse {
    file: File
  }
  export interface File {
    id?: string
    name?: string
  }
}
```
这个ytt会考虑支持吗？

**Comment by fjc0k** [comment]
ytt 是基于 YAPI 的哦，它没有 swagger、OpenAPI 那种 model（数据字典、模型之类的） 的概率，因此只能做接口级别的请求、返回类型。

**Comment by JerryChan31** [comment]
所以意思是，YAPI导入swagger的过程中把model的概念给抹平了？然后YAPI提供给ytt的数据里没有model的概念，所以无法实现

**Comment by fjc0k** [comment]
对

**Comment by JerryChan31** [comment]
了解了，谢谢
