### ISSUE TITLE
有没有办法配置多个config文件

### ISSUE THREAD

**Issue by henryzp** [fjc0k/yapi-to-typescript#45]
多人开发，希望生成不同的src/api/xx.ts文件。。。

比如说我的是a.ts，对方的是b.ts，是否有办法？

**Comment by fjc0k** [comment]
显然不太行。不过为啥要这样？

**Comment by henryzp** [comment]
就是会感觉如果项目多的话，会导致api/index.ts文件越来越大。。

还有就是运行ytt，会导致时间上的开销吧

**Comment by fjc0k** [comment]
outputFile*** 是支持项目、分类级别设置的。

**Comment by henryzp** [comment]
嗯？？outputFile不是string么？可以是数组？根据不同的token，配置不同的url输出？

**Comment by fjc0k** [comment]
> outputFile*** 是支持项目、分类级别设置的。

不是说它是人员级别的。

人员级别的你们可以搞环境变量，根据环境变量设置不同的参数。

**Comment by henryzp** [comment]
@fjc0k ，ok，懂你意思了，也就是说根据不同的环境变量，来生成不同的outputFile path？

是这样理解吧？

**Comment by fjc0k** [comment]
对
