### ISSUE TITLE
【小白 请教接口 ts使用】

### ISSUE THREAD

**Issue by chenxu-javascript** [fjc0k/yapi-to-typescript#46]
大佬， 请教一哈， 从yai拉去返回的接口是完整的。 比如说 {  result: { code: 0, status: 'success' }, data: [{  title: '业务数据' }]}
这个时候通过泛型 请求接口axios 是能获取到提示类型的。

想请问一哈， 业务使用的时候， 只需要业务数据定义的ts interface， 需要剔除返回状态吗， 实现共用。
不知道大佬是怎么在项目中实现的此类业务场景的

**Comment by fjc0k** [comment]
![image](https://user-images.githubusercontent.com/13151189/96078516-1c4c6380-0ee5-11eb-8fe0-371c5d1cafb5.png)

**Comment by chenxu-javascript** [comment]
谢谢大佬， 我想再请问一哈， 
dataKey是统一配置。
如果每个接口我期望返回的数据不一致， 应该怎么配置。比如说a 接口  { result: { code: 0, status: 'success' }, data: [{ title: '业务数据' }]}   b接口我期望获取  { result: { code: 0, status: 'success' }, data: { table: [{ table 业务数据 }], total: 10  }。

dataKey在这种情况就不能完全满足。

目前我们的解决方案是根据yapi-to-typescript 自动生成 然后copy 出去组装对应业务代码。 
再次感谢大佬

**Comment by fjc0k** [comment]
dataKey 可以在服务器级别、项目级别、分类级别配置，只要保证某个分类下的返回结果一样，就行了
