### ISSUE TITLE
当接口名是保留字或关键字时 自动生成接口报错

### ISSUE THREAD

**Issue by leitingx762** [fjc0k/yapi-to-typescript#48]
![image](https://user-images.githubusercontent.com/5674953/101129207-2153a680-363c-11eb-82f8-67b60978d585.png)

接口名为xx/delete

![image](https://user-images.githubusercontent.com/5674953/101129449-8a3b1e80-363c-11eb-9a5e-dfaa1225ae55.png)

**Comment by fjc0k** [comment]
改接口路径或者请求函数名生成函数
