### ISSUE TITLE
[新需求]接口的resBody的jsonSchema放到生成的文件中，业务代码里可以用来校验接口

### ISSUE THREAD

**Issue by inceptiongt** [fjc0k/yapi-to-typescript#49]
业务代码中校验接口，抛出错误，方便调试及测试

**Comment by fjc0k** [comment]
可以作为可选配置开启，开启则生成请求数据和返回数据的 json schema。

**Comment by inceptiongt** [comment]
项目怎样调试啊，用vscode自带的调试功能可以吗

**Comment by fjc0k** [comment]
这种比较深入的需求我来实现吧 😀  没有调试  我都是写完写个测试  没问题就发版

**Comment by inceptiongt** [comment]
那什么时候可以完成呢

**Comment by inceptiongt** [comment]
> 这种比较深入的需求我来实现吧 😀 没有调试 我都是写完写个测试 没问题就发版

![image](https://user-images.githubusercontent.com/20478779/101478749-1e361e80-398c-11eb-929e-919d4eed33ca.png)
试了下，launch.js如图配置后，可以在VSCode的debugging面板里调试了

**Comment by fjc0k** [comment]
已支持，试试最新版，一个配置示例：

```javascript
import { defineConfig } from 'yapi-to-typescript'

export default defineConfig({
  serverUrl: 'https://petstore.swagger.io/v2/swagger.json',
  serverType: 'swagger',
  outputFilePath: 'api/index.ts',
  jsonSchema: {
    enabled: true,
  },
  projects: [
    {
      token: '',
      categories: [
        {
          id: 0,
        },
      ],
    },
  ],
})
```

**Comment by fjc0k** [comment]
> > 这种比较深入的需求我来实现吧 😀 没有调试 我都是写完写个测试 没问题就发版
> 
> ![image](https://user-images.githubusercontent.com/20478779/101478749-1e361e80-398c-11eb-929e-919d4eed33ca.png)
> 试了下，launch.js如图配置后，可以在VSCode的debugging面板里调试了

👍 可以试试
