### ISSUE TITLE
ytt command SyntaxError: Unexpected token export

### ISSUE THREAD

**Issue by Derek-Hu** [fjc0k/yapi-to-typescript#5]
> ytt

(node:28805) UnhandledPromiseRejectionWarning: /Users/myname/workspaces/myProject/ytt.config.ts:51
export default config;
^^^^^^

SyntaxError: Unexpected token export

version:
node: v8.11.4
npm: 5.6.0

**Comment by fjc0k** [comment]
将 `tsconfig.json` 中的 `compilerOptions.module` 设为 `commonjs` 即可，这块需要增强下，不与项目的 `tsconfig.json` 产生关联。
