### ISSUE TITLE
[feature request] generator 提供外部实现

### ISSUE THREAD

**Issue by kamilic** [fjc0k/yapi-to-typescript#56]
能不能把 generator 解耦合，让外部可以提供自己的 generator，利用你的数据来生成自己的代码？

**Comment by kamilic** [comment]
@fjc0k 你好，有考虑这个功能吗，如果需要我可以尝试写一下

**Comment by fjc0k** [comment]
> @fjc0k 你好，有考虑这个功能吗，如果需要我可以尝试写一下

不考虑哈
