### ISSUE TITLE
存在路径参数时，生成代码报错

### ISSUE THREAD

**Issue by GoldSubmarine** [fjc0k/yapi-to-typescript#58]
![image](https://user-images.githubusercontent.com/22909744/133717475-22dae741-52d5-4de9-a6e9-b9fb02d9ed51.png)
![image](https://user-images.githubusercontent.com/22909744/133717508-50f130b4-da79-4301-9e04-5cabe883643b.png)
![image](https://user-images.githubusercontent.com/22909744/133717716-b5913f43-aa64-4827-91ca-1b8f9367a36a.png)

**Comment by fjc0k** [comment]
你自己问题，不会用changeCase转一下？
