### ISSUE TITLE
个人小小的期望

### ISSUE THREAD

**Issue by Estelle00** [fjc0k/yapi-to-typescript#7]
希望下个版本生成代码能够分成文件
比如分组id 可以扩展生成文件名称fileName
或者扩展getFlilName方法

**Comment by fjc0k** [comment]
感谢建议。

我理解的，你的意思是：

> 希望在生成 api 文件时，不同的分组放在不同的文件。

那么我想知道，为什么这样做？有什么应用场景？

**Comment by Estelle00** [comment]
1、希望在做多页面模式的时候，能减少部分不必要的内容
2、本地目录看上去更清晰，方便查看
以上是我个人的想法

补充：拆分是想根据是否存在fileName判断是否拆分，仅建议哈

**Comment by fjc0k** [comment]
嗯嗯，了解。

> 1、希望在做多页面模式的时候，能减少部分不必要的内容

在打包时，Webpack 的 tree-shaking 会自动把没用到的接口剔除的。

> 2、本地目录看上去更清晰，方便查看

个人认为，查看与修改应该在 yapi 平台完成，在本地就不应该显式地以分类区别接口，有接口函数名、类型名足矣。
