### ISSUE TITLE
能否增加配置项，支持关闭自动将query参数拼接至path上的功能

### ISSUE THREAD

**Issue by YNestA** [fjc0k/yapi-to-typescript#71]
![image](https://user-images.githubusercontent.com/10988530/159230324-f83ee9b8-55ab-4188-9064-58d2db94e6f8.png)
这段逻辑能否支持配置是否关闭呢？我们需要自己对path和query参数做一些特殊的处理，所以希望能有配置项让path和参数保留原本的样子。同时作为替代，能否对RequestFunctionParams区分开body和query的参数？
如果能支持，非常感谢🙏

**Comment by hezhengjie** [comment]
这块主要是对数组并没有进行兼容处理，导致数组的query参数拼接到url上是有问题的

**Comment by fjc0k** [comment]
试试新版。https://fjc0k.gitee.io/yapi-to-typescript/handbook//config.html#querystringarrayformat
