### ISSUE TITLE
请求参数 data 应当有必需属性 id

### ISSUE THREAD

**Issue by zh-lx** [fjc0k/yapi-to-typescript#76]
<img width="697" alt="image" src="https://user-images.githubusercontent.com/73059627/198966405-48e97712-52d7-46ba-8ec8-a72c14bed9a3.png">

**Comment by KillerAMiRa** [comment]
![image](https://user-images.githubusercontent.com/61682091/220048839-99e16236-d16e-4f9f-9d72-a45e00fd43d2.png)
瞧瞧是不是版本问题

**Comment by zh-lx** [comment]
感谢，确实是我用的老版本
